Algoritmo "Exercicio Medidas"



Var


A, B, C, areaA, areaB, areaC : real





Inicio

escreva("Insira a medida de A: ")
leia(A)
escreva("Insira a medida de B: ")
leia(B)
escreva("Insira a medida de C: ")
leia(C)


areaA <- (A*A)
areaB <- (A*B/2)
areaC <- ((A+B)*C/2)

escreval("Area do quadrado = ",areaA:8:4)
escreval("Area do triangulo = ",areaB:8:4)
escreval("Area do trapezio = ",areaC:8:4)







Fimalgoritmo