Algoritmo "Idade"



Var

nome1,nome2 : caractere
idade1,idade2 : inteiro
media : real






Inicio

      escreva("O nome da primeira pessoa:")
      leia(nome1)
      escreva("Idade :")
      leia(idade1)
      escreva("O nome da segunda pessoa:")
      leia(nome2)
      escreva("Idade :")
      leia(idade2)
      
      
      
      media <- (idade1+idade2)/ 2

      escreval
      escreval("A idade media das duas pessoas e: ",media)








Fimalgoritmo