Algoritmo "Exercicio Terreno"

Var

 L, C, mQ, preco, area : real


Inicio



      escreva("Digite a largura do terreno: ")
      leia (L)
      escreva("Agora digite o comprimento do terreno: ")
      leia (C)
      escreva("Digite o valor do metro quadrado: ")
      leia (mQ)


      area <- (C*L)
      preco <- (area*mq)
      
      
 
 
 
 
 
 
 
   escreval
   escreval( " Area do terreno = ",area:8:2)
   escreval(" O preco do terreno:", preco:8:2)







Fimalgoritmo