Algoritmo "Problema_senhafixa"


Var

 senha, valor : inteiro
 




Inicio

valor <- 2002

 escreva("Digite a senha : ")
 leia(senha)
 
 
 enquanto senha <> valor faca
      escreval("Senha Invalida!!")
      escreval
      escreva("Tente novamente : ")
      leia(senha)
      
    se senha = valor entao
       escreval("Acesso permitido!")
       
    fimse
    

fimenquanto



















fimAlgoritmo