Algoritmo "Problema_crescente"


Var

x,y : inteiro

Inicio

x <- 0
y <- 0


escreval("Digite dois numeros : ")
leia(x)
leia(y)


enquanto x <> y faca

 se x > y entao

   escreval("----------------------------------------------------------")
   escreval("DECRESCENTE !!!")
   escreval("----------------------------------------------------------")
   
   senao

 se x < y entao

    escreval("----------------------------------------------------------")
    escreval("CRESCENTE !!!")
    escreval("----------------------------------------------------------")



       fimse
   fimse


   escreval("Digite outro dois numeros: ")
   leia(x)
   leia(y)


   
fimenquanto











Fimalgoritmo